name: fake-faces
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - click
  - eli5
  - jupyter
  - jupytext
  - mtcnn
  - numpy
  - pillow
  - pylint
  - pytest
  - scikit-learn
  - tensorflow-gpu
