name: fake-faces
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - click
  - eli5
  - jupyter
  - jupytext
  - mtcnn
  - numpy
  - pillow
  - pylint
  - pytest
  - python-dotenv
  - python-slugify
  - scikit-learn
  - tensorflow-gpu
  - pip:
      - azure-functions
      - questionary
