# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='fake-faces',
    version='0.1.0',
    python_requires='<3.10,>=3.6',
    author='Alex Kyllo',
    author_email='alex.kyllo@gmail.com',
    entry_points={"console_scripts": ["fake-faces = fake_faces.cli:main"]},
    packages=['fake_faces', 'fake_faces.experiments', 'fake_faces.models'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'azure-functions==1.*,>=1.5.0', 'click==7.*,>=7.1.2',
        'eli5==0.*,>=0.10.1', 'matplotlib==3.*,>=3.3.2', 'mtcnn==0.*,>=0.1.0',
        'numpy==1.*,>=1.18.0', 'pydot==1.*,>=1.4.1',
        'python-dotenv==0.*,>=0.15.0', 'python-slugify==4.*,>=4.0.1',
        'questionary==1.*,>=1.8.1', 'scikit-learn==0.*,>=0.23.2',
        'tensorflow==2.*,>=2.3.1'
    ],
    extras_require={
        "dev": [
            "black==20.*,>=20.8.0.b1", "pyclean==2.*,>=2.0.0",
            "pylint==2.*,>=2.6.0", "pytest==5.*,>=5.2.0"
        ]
    },
)
